---
# tasks file for ansible-role-change_shell

- name: Configure user shell for macOS
  import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

# TO DO: configure user shell for Linux distros
 

